(function ensightenInit(){var ensightenOptions = {client: "turner", clientId: 1511, publishPath: "nba-prod", isPublic:0, serverComponentLocation: "nexus.ensighten.com/turner/nba-prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/turner/nba-prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Mon Aug 07 17:39:48 GMT 2017", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function l(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function m(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function n(){for(var a=b.dataDefinitionIds.length,d=!0,e=0;e<a;e++){var c=b.dataDefinitions[b.dataDefinitionIds[e]];if(!c||
null==c.endRegistration){d=!1;break}}d&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=f.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:f.interval||100,erLoc:f.errorLocation||c.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||c.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||c.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.runRuleIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var d=0;d<a.dependencies.length;d++)if(!1===a.dependencies[d]())return;
a.execute()}};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;c.DependencyNotAvailableException=l;m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.BeaconException=m;c.checkForInvalidDependencies=function(a,d,e,h){for(a=0;a<e.length;a++)if("DEPENDENCYNEVERAVAILABLE"===e[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(h[a])),d&&-1!==d&&c.allDeploymentIds.push(d),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var d=(c.currSec||0)%20,b=c.options.beaconSamplingSeedValue;-1===b?a=!0:0!==d&&0===b%d&&(a=!0)}catch(h){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(d){window[ensightenOptions.ns].reportException(d)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(c.runDeploymentIds.push(this.deploymentId),c.runRuleIds.push(this.id)),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);
-1!==a.deploymentId&&c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};b.getRuleList=function(){return c.ruleList};b.clearRuleList=function(){c.ruleList=[]};b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunRuleIds=function(){return c.runRuleIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:
!1};c.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);
this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,d,e,h){var p=
document.getElementsByTagName("script"),g;h=void 0!==h?h:!0;if(void 0!==d?d:1)for(g=0;g<p.length;g++)if(p[g].src===a&&p[g].readyState&&/loaded|complete/.test(p[g].readyState))return;if(e){e=1==e&&"object"==typeof b.scDataObj?b.scDataObj:e;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));d=window.location.href;"object"===typeof e&&e.PageID&&(d=e.PageID,delete e.PageID);if("object"===typeof e)for(g in e){g=~d.indexOf("#")?d.slice(d.indexOf("#"),d.length):"";d=d.slice(0,g.length?d.length-g.length:
d.length);d+=~d.indexOf("?")?"&":"?";for(k in e)d+=k+"="+e[k]+"&";d=d.slice(0,-1)+g;break}a+="?";h&&(a+="r="+c.rand+"&");a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(d)}(function(a,b,d){var e=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in e){if(!e[0]){setTimeout(arguments.callee,25);return}e=e[0]}var a=b.createElement("script");a.src=d;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};e.insertBefore(a,
e.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,e){var d=document.getElementsByTagName("script"),c;e=d[0];for(c=0;c<d.length;c++)if(d[c].src===a&&d[c].readyState&&/loaded|complete/.test(d[c].readyState))try{b()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}d=document.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;d.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.onload=d.onreadystatechange=function(){if(!this.readyState||
"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(g){window[ensightenOptions.ns].reportException(g)}}};e.parentNode.insertBefore(d,e)};b.unobtrusiveAddEvent=function(a,b,e){try{var d=a[b]?a[b]:function(){};a[b]=function(){e.apply(this,arguments);return d.apply(this,arguments)}}catch(p){window[ensightenOptions.ns].reportException(p)}};b.anonymous=function(a,d){return function(){try{b.currentRuleId=
d?d:"anonymous",a()}catch(e){window[ensightenOptions.ns].reportException(e)}}};b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var d,e=0;e<a.length;++e)if(d=b.getRule(parseInt(a[e],10)),!d||!d.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,
h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===
typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,d,e,f,p){var g=[];if(!c.checkForInvalidDependencies(d,f,e,p)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:f||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var d=a.length,e=0;e<d;e++){var c=a[e];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var f=!1,g=b.dataDefinitionIds.length,l=0;l<g;l++)if(b.dataDefinitionIds[l]===c){f=!0;break}f||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;n()};b.DataDefinition=function(a,b){this.id=
a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,d){var e=b.dataDefinitions[d];e||(e=new b.DataDefinition(d,a),b.dataDefinitions[d]=e);e.startRegistrationTime||(e.startRegistration(),e.registrationFn(),e.endRegistration());b.pageSpecificDataDefinitionsSet&&n()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=
!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,e=a.length;b<e;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&
"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=
function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var r=function(){var a=[],b=!1,e=!1;return{add:function(d){b&&!e?d():"function"==typeof d&&(a[a.length]=d)},exec:function(){e=!0;do{var d=a;a=[];b=!0;for(var c=0;c<d.length;c++)try{d[c].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);e=!1},haveRun:function(){return b}}};b.new_fArray=
function(){return r()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?
c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(d){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",
function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&"complete"===document.readyState&&(b.executionState.DOMParsed=!0,b.executionState.DOMLoaded=!0);"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],d,e,h,l,g=0;g<c.ruleList.length;++g)e=c.ruleList[g],h=e.executionData.hasRun?"1":"0",l=e.deploymentId.toString()+"|"+e.id.toString()+"|"+h,a.push(l);
d="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+d+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(q){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new c.BeaconException(q),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){var f=f.timing||{},l=f.navigationStart||0,m={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var n="&ns="+encodeURIComponent(f.navigationStart);for(var c in m)if(void 0!==f[c]){var b=f[c]-l;n+="&"+m[c]+"="+(0<b?encodeURIComponent(b):0)}else n+="&"+m[c]+"=-1";window[ensightenOptions.ns].timing=n;c=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";n=f.indexOf(".com/");l=f.indexOf("/code/");f=f.substring(n+4,l)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+c+f)}}});
	
if (!window[ensightenOptions.ns].data) {
/*
 MIT License (c) copyright 2011-2013 original author or authors  MIT License (c) copyright 2013 original author or authors */
window.JSON&&"object"===typeof JSON||(window[ensightenOptions.ns].JSON={});
(function(){function d(a){return 10>a?"0"+a:a}function n(a){c.lastIndex=0;return c.test(a)?'"'+a.replace(c,function(a){var e=b[a];return"string"===typeof e?e:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function k(d,e){var b,f=h,c=e[d];c&&"object"===typeof c&&"function"===typeof c.toJSON&&(c=c.toJSON(d));"function"===typeof g&&(c=g.call(e,d,c));switch(typeof c){case "string":return n(c);case "number":return isFinite(c)?String(c):"null";case "boolean":case "null":return String(c);
case "object":if(!c)return"null";h+=a;var m=[];if("[object Array]"===Object.prototype.toString.apply(c)){var l=c.length;for(b=0;b<l;b+=1)m[b]=k(b,c)||"null";var r=0===m.length?"[]":h?"[\n"+h+m.join(",\n"+h)+"\n"+f+"]":"["+m.join(",")+"]";h=f;return r}if(g&&"object"===typeof g)for(l=g.length,b=0;b<l;b+=1){if("string"===typeof g[b]){var t=g[b];(r=k(t,c))&&m.push(n(t)+(h?": ":":")+r)}}else for(t in c)Object.prototype.hasOwnProperty.call(c,t)&&(r=k(t,c))&&m.push(n(t)+(h?": ":":")+r);r=0===m.length?"{}":
h?"{\n"+h+m.join(",\n"+h)+"\n"+f+"}":"{"+m.join(",")+"}";h=f;return r}}var l=window.JSON?window.JSON:window[ensightenOptions.ns].JSON;"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+d(this.getUTCMonth()+1)+"-"+d(this.getUTCDate())+"T"+d(this.getUTCHours())+":"+d(this.getUTCMinutes())+":"+d(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});
var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h,a,b={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},g;"function"!==typeof l.stringify&&(l.stringify=function(c,e,b){var d;a=h="";if("number"===typeof b)for(d=0;d<b;d+=1)a+=" ";else"string"===typeof b&&(a=b);if((g=e)&&"function"!==
typeof e&&("object"!==typeof e||"number"!==typeof e.length))throw Error("JSON.stringify");return k("",{"":c})});"function"!==typeof l.parse&&(l.parse=function(a,e){function c(a,b){var g,d=a[b];if(d&&"object"===typeof d)for(g in d)if(Object.prototype.hasOwnProperty.call(d,g)){var f=c(d,g);void 0!==f?d[g]=f:delete d[g]}return e.call(a,b,d)}a=String(a);f.lastIndex=0;f.test(a)&&(a=a.replace(f,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){var b=eval("("+a+")");return"function"===typeof e?c({"":b},""):b}throw new SyntaxError("JSON.parse");})})();
window[ensightenOptions.ns].when=function(){function d(a,e,b,c){return k(a).then(e,b,c)}function n(a){this.then=a}function k(a){return l(function(e){e(a)})}function l(e){function c(a){m&&(q=f(a),b(m,q),m=r)}function d(a){c(h(a))}function g(e){m&&b(m,a(e))}var q,m=[];try{e(c,d,g)}catch(F){d(F)}return new n(function(a,e,c){return l(function(b,d,g){m?m.push(function(f){f.then(a,e,c).then(b,d,g)}):p(function(){q.then(a,e,c).then(b,d,g)})})})}function f(a){return a instanceof n?a:a!==Object(a)?c(a):l(function(e,
b,d){p(function(){try{var g=a.then;"function"===typeof g?A(g,a,e,b,d):e(c(a))}catch(y){b(y)}})})}function c(a){var e=new n(function(b){try{return"function"==typeof b?f(b(a)):e}catch(E){return h(E)}});return e}function h(a){var e=new n(function(b,c){try{return"function"==typeof c?f(c(a)):e}catch(G){return h(G)}});return e}function a(e){var b=new n(function(c,d,g){try{return"function"==typeof g?a(g(e)):b}catch(y){return a(y)}});return b}function b(a,e){p(function(){for(var b,c=0;b=a[c++];)b(e)})}function g(a,
e,b,c,g){u(2,arguments);return d(a,function(a){return l(function(b,c,g){function f(a){k(a)}function p(a){x(a)}var q;var m=a.length>>>0;var u=Math.max(0,Math.min(e,m));var h=[];var t=m-u+1;var l=[];if(u){var k=function(a){l.push(a);--t||(x=k=v,c(l))};var x=function(a){h.push(a);--u||(x=k=v,b(h))};for(q=0;q<m;++q)q in a&&d(a[q],p,f,g)}else b(h)}).then(b,c,g)})}function m(a,b,c,g){u(1,arguments);return e(a,z).then(b,c,g)}function e(a,e){return d(a,function(a){return l(function(b,c,g){var f,p;var q=f=
a.length>>>0;var m=[];if(q){var u=function(a,f){d(a,e).then(function(a){m[f]=a;--q||b(m)},c,g)};for(p=0;p<f;p++)p in a?u(a[p],p):--q}else b(m)})})}function p(a){1===t.push(a)&&B(q)}function q(){for(var a,e=0;a=t[e++];)a();t=[]}function u(a,e){for(var b,c=e.length;c>a;)if(b=e[--c],null!=b&&"function"!=typeof b)throw Error("arg "+c+" must be a function");}function v(){}function z(a){return a}d.defer=function(){var a,e;var b={promise:r,resolve:r,reject:r,notify:r,resolver:{resolve:r,reject:r,notify:r}};
b.promise=a=l(function(c,g,d){b.resolve=b.resolver.resolve=function(b){if(e)return k(b);e=!0;c(b);return a};b.reject=b.resolver.reject=function(b){if(e)return k(h(b));e=!0;g(b);return a};b.notify=b.resolver.notify=function(a){d(a);return a}});return b};d.resolve=k;d.reject=function(a){return d(a,h)};d.join=function(){return e(arguments,z)};d.all=m;d.map=e;d.reduce=function(a,b){var e=A(C,arguments,1);return d(a,function(a){var c=a.length;e[0]=function(a,e,g){return d(a,function(a){return d(e,function(e){return b(a,
e,g,c)})})};return H.apply(a,e)})};d.any=function(a,b,e,c){return g(a,1,function(a){return b?b(a[0]):a[0]},e,c)};d.some=g;d.isPromise=function(a){return a&&"function"===typeof a.then};n.prototype={otherwise:function(a){return this.then(r,a)},ensure:function(a){function b(){return k(a())}return this.then(b,b).yield(this)},yield:function(a){return this.then(function(){return a})},spread:function(a){return this.then(function(b){return m(b,function(b){return a.apply(r,b)})})},always:function(a,b){return this.then(a,
a,b)}};var r;var t=[];var I=setTimeout;var B="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?process.nextTick:function(a){I(a,0)};var w=Function.prototype;var D=w.call;var A=w.bind?D.bind(D):function(a,b){return a.apply(b,C.call(arguments,2))};w=[];var C=w.slice;var H=w.reduce||function(a){var b=0;var e=Object(this);var c=e.length>>>0;var g=arguments;if(1>=g.length)for(;;){if(b in e){g=e[b++];break}if(++b>=
c)throw new TypeError;}else g=g[1];for(;b<c;++b)b in e&&(g=a(g,e[b],b,e));return g};return d}();
(function(){function d(d,c){return k.all(c||[],function(c){return d.apply(null,c)})}function n(f){var c=l.call(arguments,1);return function(){return d(f,c.concat(l.call(arguments)))}}var k=window[ensightenOptions.ns].when;var l=[].slice;k.apply=d;k.call=function(f){return d(f,l.call(arguments,1))};k.lift=n;k.bind=n;k.compose=function(f){var c=l.call(arguments,1);return function(){var h=l.call(arguments),h=d(f,h);return k.reduce(c,function(a,b){return b(a)},h)}}})();
window[ensightenOptions.ns].data=function(d,n){function k(a,b){this.name="DataDefinitionException";this.message=b||"Data definitions cannot be resolved as there are invalid id(s): "+a}var l,f={engines:{memory:{get:function(a){if(c.utils.isArray(a)){for(var b=[],g=0;g<a.length;g++)b.push(f.data[a[g]]);return d[ensightenOptions.ns].when.resolve(b)}b=f.dataDefinitions[a]||{storage:{get:function(){}}};b=b.storage.get(b);f.data[a]=b;return d[ensightenOptions.ns].when.resolve(f.data[a])},set:function(a,
b){if(c.utils.isArray(a))for(var g in a)f.data[a[g]]=b[g];else f.data[a]=b;return d[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(c.utils.isArray(a))for(var b in a)delete f.data[a[b]];else delete f.data[a];return d[ensightenOptions.ns].when.resolve(!0)},clear:function(a){f.data={};f.definitions={};return d[ensightenOptions.ns].when.resolve(!0)},all:function(){return d[ensightenOptions.ns].when.resolve(f.data)}}},normalizeInputArgs:function(a,b){var g={key:[],val:n},d;if(c.utils.isPlainObject(a))for(d in g.val=
[],a)g.key.push(d),g.val.push(a[d]);else c.utils.isArray(a),g.key=a,g.val=b;return g},definitions:{},data:{}},c={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(b){return a}}}},h=function(){return d[ensightenOptions.ns].when.reject("Not Implemented.")};k.prototype=Error();k.prototype||
(k.prototype={});k.prototype.constructor=k;f.DataDefinitionException=k;f.checkForInvalidDataDefinitions=function(a){c.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),-1<a.indexOf("invalid_id"))?(d[ensightenOptions.ns].reportException(new f.DataDefinitionException(a)),!0):!1};f.collectAvailableDataDefinitions=function(a){for(var b=[],g=0;g<a.length;g++){var m=parseInt(a[g],10),e=d[ensightenOptions.ns].dataDefinitions[m];if(null===e||e===n)if(e=c.storage.session.get({id:m}),null!==e&&
e!==n)c.set(m,e),f.dataDefinitions[m]={id:m,load:"visitor",storage:c.storage.visitor,missingDDFromCache:!0},b.push(d[ensightenOptions.ns].data.get(""+m));else return d[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Invalid data definition used: "+m)),{promises:[],isInvalid:!0};else b.push(d[ensightenOptions.ns].data.get(a[g]))}return{promises:b,isInvalid:!1}};f.getSync=function(a){function b(a){var b=a.extract||m,c=a.transform||e,d=!1,f=null,p=null;try{f=b()}catch(w){f=null,
d=!0}try{p=c(f)}catch(w){p=null,d=!0}d&&g.push(a.id);return p}var g=[],m=function(){return document},e=function(a){return null!==a&&a!==n?a.toString():null},p=parseInt(a);a="string"===typeof a?a.split("."):[];var q={},u="";isNaN(p)?3==a.length&&(q=c.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2])):q=c.getDataDefinitionById(p);u=q.load&&q.load.match(/(session|visitor)/i)&&q.storage&&q.storage.get?q.storage.get(q):b(q);0<g.length&&d[ensightenOptions.ns].reportException(new f.DataDefinitionException(g,
"Error resolving data definitions synchronously: "+g));return u};f.dataDefinitions={};f.dataDefinitionsBySourceCollName={};c.defineEngine=function(a,b){var c,m=["get","set","remove","clear","all"];f.engines[a]=b;if(!b.returnsPromise)for(c=0;c<m.length;c++){var e=m[c];b[e]=d[ensightenOptions.ns].when.lift(b[e])}};c.storage={instance:{set:function(a,b){},get:function(a){return f.getSync(a.id)}},page:{set:function(a,b){},get:function(a){return f.data[a.id]}},session:{set:function(a,b){var g=c.storage.session.get({id:a}),
f=new Date,e=f.getTime();f.setTime(e+18E5);null!=g&&(b=g);d[ensightenOptions.ns].data.cookie.utils.set(a,b,{expires:f.toGMTString()});g={expires:f.getTime(),value:b};d[ensightenOptions.ns].data.local.utils.set(a,g)},get:function(a){var b=d[ensightenOptions.ns].data.cookie.utils.get(a.id),c=d.JSON&&d.JSON.stringify?d.JSON:d[ensightenOptions.ns].JSON,c=c||{},f=new Date,f=f.getTime();if(null===b){try{var e=c.parse(d[ensightenOptions.ns].data.local.utils.get(a.id))}catch(p){e=null}null!=e&&(e.expires=
+e.expires,f<=e.expires?b=e.value:""==e.expires&&e.value!=n?b=e.value:d[ensightenOptions.ns].data.local.utils.remove(a.id))}return b}},visitor:{set:function(a,b){var g=c.storage.session.get({id:a});null!=g&&(b=g);d[ensightenOptions.ns].data.cookie.utils.set(a,b);d[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:b})},get:function(a){return c.storage.session.get(a)}}};c.getEngine=c.engine=function(a){return a?f.engines[a]||{get:h,set:h,remove:h,clear:h,all:h}:f.engines};c.all=function(a){return d[ensightenOptions.ns].data.engine(a||
"memory").all()};c.get=function(a,b,c){b=b||"memory";c=c||{};-1<a.indexOf(",")&&(a=a.split(","));a=f.normalizeInputArgs(a);return c.wait?f.getWait(a.key,d[ensightenOptions.ns].data.engine(b),c):f.data&&f.data.hasOwnProperty(a.key)?d[ensightenOptions.ns].data.engine(b).get(a.key):f.getWaitForKey(a.key,d[ensightenOptions.ns].data.engine(b),c)};f.getWait=function(a,b,g){var f=+new Date,e=d[ensightenOptions.ns].when.defer(),p=function(){var c=b.get(a);if(-1===g.wait)return c;c.then(function(a){g.setCheck(a)?
e.resolve(a):setTimeout(q,g.interval)},function(a){setTimeout(q,g.interval)})},q=function(){var a=+new Date-f;-1!==g.wait&&a<g.wait?p():e.reject("Timeout")};g.interval=g.interval||500;g.wait=g.wait||5E3;c.utils.isArray(a)?g.setCheck=g.setCheck||function(a){for(var b=!0,e=0;e<a.length;e++)b=b&&!!a[e];return b}:g.setCheck=g.setCheck||function(a){return!!a};p();return e.promise};f.getWaitForKey=function(a,b,c){var g=d[ensightenOptions.ns].when.defer(),e=function(){if(f.data&&f.data.hasOwnProperty(a)){var e=
b.get(a);if(-1===c.wait)return e;e.then(function(a){g.resolve(a)},function(a){g.reject(a)})}else setTimeout(p,c.interval)},p=function(){e()};c.interval=c.interval||100;c.wait=c.wait||1;e();return g.promise};c.set=function(a,b,c){var g=f.normalizeInputArgs(a,b);Array.prototype.slice.call(arguments);return d[ensightenOptions.ns].data.engine(c||"memory").set(g.key,g.val)};c.remove=function(a,b){return d[ensightenOptions.ns].data.engine(b||"memory").remove(a)};c.clear=function(a){return d[ensightenOptions.ns].data.engine(a||
"memory").clear()};c.define=function(a,b){b&&(a.name=b.id||b.name);if(!a.name)return d[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));a.id=a.name;var g=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return d[ensightenOptions.ns].when.resolve()};a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=d[ensightenOptions.ns].data.engine("memory");a.storage=c.storage[g.toLowerCase()]||
c.storage.page;var m=a.extract||function(){return document},e=a.transform||function(a){return a},p=function(b,c){var e=[];e.push(a.persist.set(b,c));a.storage.set(a.id,c);"object"==typeof d[ensightenOptions.ns].data.dataExport&&d[ensightenOptions.ns].data.dataExport(b,c,a.collection);d[ensightenOptions.ns].when.all(e).then(function(a){q.resolve(a)},function(a){q.reject(a)})},q=d[ensightenOptions.ns].when.defer();try{var h=a.trigger()}catch(v){d[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,
'"'+v+'" error caught in Data Definition trigger: '+a.dataDefName+", ID:"+a.id+". Using bottom of body trigger.")),h=d[ensightenOptions.ns].data.bottomOfBodyTrigger()}h.then(function(){q.resolve(d[ensightenOptions.ns].when.reduce([function(){try{return m()}catch(v){return d[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,'"'+v+'" error caught in Data Definition extractor: '+a.dataDefName+", ID:"+a.id+".")),null}}(),function(){try{return e.apply(this,arguments)}catch(v){return d[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,
'"'+v+'" error caught in Data Definition transformer: '+a.dataDefName+", ID "+a.id+".")),null}},p],function(b,c,e,d){if(1==e)return c(b);2==e&&c(a.name,b)}))},function(a){q.reject(a)});f.dataDefinitions[a.id]=a;f.dataDefinitionsBySourceCollName[""+a.source+"."+a.collection+"."+a.dataDefName]=a;return q.promise};c.checkConditions=function(a){var b,g={lt:function(a,b){var c=+a,e=+b;return isNaN(c)||isNaN(e)?(d[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+
a+", compareTo: "+b)),!1):c<e},gt:function(a,b){var c=+a,e=+b;return isNaN(c)||isNaN(e)?(d[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+b)),!1):c>e},eql:function(a,b){return a==b},exists:function(a,b){return null==a||a==n||""==a?!1:!0},re:function(a,b,c){b=new RegExp(b,c?"i":"");try{return a.match(b)}catch(u){return!1}},starts:function(a,b,d){b=c.utils.escapeRegEx(b);return g.re(a,"^"+b,d)},ends:function(a,
b,d){b=c.utils.escapeRegEx(b);return g.re(a,b+"$",d)},contains:function(a,b,d){b=c.utils.escapeRegEx(b);return g.re(a,".*"+b+".*",d)}};g.is=g.eql;g["starts with"]=g.starts;g["ends with"]=g.ends;g["is greater than"]=g.gt;g["is less than"]=g.lt;g.matches=g.re;for(b=0;b<a.values.length;b++){var m=(a.customComparator?a.customComparator[b]?a.customComparator[b]:g[a.comparators[b]]:g[a.comparators[b]])(a.values[b],a.compareTo[b],a.caseInsensitive?a.caseInsensitive[b]||!1:!1);a.not[b]&&(m=!m);if(!m)return!1}return!0};
c.triggerPromise=function(a,b,c){c=c||5E3;var f=+new Date,e=d[ensightenOptions.ns].when.defer();(function(){var d=a();d!=b?e.resolve(d):+new Date-f<c?setTimeout(arguments.callee,200):e.reject("timed out")})();return e.promise};c.timeoutPromise=function(a,b){var c=d[ensightenOptions.ns].when.defer();b=b||800;a.then(c.resolve,c.reject);setTimeout(function(){c.reject(Error("timed out"))},b);return c.promise};c.delayTrigger=function(a){a=a||10;var b=d[ensightenOptions.ns].when.defer();setTimeout(function(){b.resolve()},
a);return b.promise};c.delayUntilTrigger=function(a,b,c,f){c=c||null;f=f||200;var e=+new Date,g=d[ensightenOptions.ns].when.defer();(function(){var d=a();d!=b?g.resolve(d):c?+new Date-e<c?setTimeout(arguments.callee,f):g.reject("timed out"):setTimeout(arguments.callee,f)})();return g.promise};f.applyTrigger=function(a){var b=d[ensightenOptions.ns].when.defer();a(function(){b.resolve(!0)});return b.promise};c.immediateTrigger=function(){return f.applyTrigger(d[ensightenOptions.ns].bindImmediate)};
c.bottomOfBodyTrigger=function(){return f.applyTrigger(d[ensightenOptions.ns].bindDOMParsed)};c.whenValueExistsTrigger=function(){return d[ensightenOptions.ns].when.resolve(this.extract())};c.afterEnsightenCompleteTrigger=function(){return f.applyTrigger(d[ensightenOptions.ns].bindPageSpecificCompletion)};c.afterElementsDownloadedTrigger=function(){return f.applyTrigger(d[ensightenOptions.ns].bindDOMLoaded)};c.getAllDataDefinitionsOnCurrentPage=function(){return f.dataDefinitions};c.getAllDataDefinitionsOnCurrentPage_S_C_N=
function(){return f.dataDefinitionsBySourceCollName};c.getDataDefinitionById=function(a){return f.dataDefinitions[a||-1]||{}};c.getDataDefinitionBySourceCollectionName=function(a,b,c){return f.dataDefinitionsBySourceCollName[""+a+"."+b+"."+c]||{}};c.getDataDefinitionByPercentSyntax=function(a){a=(""+a).split("_");return 1>a.length?{}:f.dataDefinitions[a[1]]||{}};c.resolve=function(a,b){var g=this;var h=null;if(!f.checkForInvalidDataDefinitions(a))if(b)d[ensightenOptions.ns].bindDataDefinitionComplete(function(){var c=
f.collectAvailableDataDefinitions(a);c.isInvalid||d[ensightenOptions.ns].when.all(c.promises).then(function(c){try{b.apply(g,c)}catch(v){d[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+v))}},function(b){d[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+b))})});else{var e=[];h=a;c.utils.isArray(a)||(h=[a]);for(var p=0;p<h.length;p++)e.push(f.getSync(h[p]));
return h=c.utils.isArray(a)?e:e[0]}};c.extract=function(a,b){var c="",f=function(a,b){var c=~b.indexOf("#")?b.split("#")[1]:"",e=c?0:~b.indexOf("[")?parseInt(b.match(/\[(\d+)\]/)[1]):0,d=(c?b.split("#")[0]:e?b.split("[")[0]:b).toLowerCase();if(a==document&&"html"==d&&0==e)return document.getElementsByTagName("html")[0];if(~b.indexOf("#"))return document.getElementById(b.split("#")[1]);var f=a.firstChild;if(!f)return null;for(var g=0,e=0!=e?e-1:e;f;){if(1==f.nodeType){if(f.tagName.toLowerCase()==d&&
""!=c&&f.id==c||f.tagName.toLowerCase()==d&&g==e&&""==c)return f;f.tagName.toLowerCase()==d&&g++}f=f.nextSibling}},e=function(a,b){a=a.split("/");for(var c=f(b||document,a[1]),e=2;e<a.length;e++){if(null==c)return null;c=f(c,a[e])}return c},p=function(){for(var a={},b=d.document.getElementsByTagName("META")||[],c=0,e=b.length;c<e;c++){var f=b[c].name||b[c].getAttribute("property")||"";0!==f.length&&(a[f]=b[c].content)}return a}(),h=function(a){var b=p[a];if(b)return b;for(var b=d.document.getElementsByTagName("META")||
[],c=0,e=b.length;c<e;c++){var f=b[c].name||b[c].getAttribute("property")||"";if(a==f)return b[c].content}},k=function(a){return(val=(new RegExp("&"+a+"=([^&]*)")).exec(d.location.search.replace(/^\?/,"&")))?val[0].split("=")[1]:""},l=function(a){return(val=(new RegExp("^"+a+"=.*|;\\s*"+a+"=.*")).exec(d.document.cookie))?val[0].split("=")[1].split(";")[0]:""},n=function(a){(a=r(a))&&a.nodeType&&1==a.nodeType&&(a=a.value||a.innerHTML||"");return a.toString().replace(/\n|\r|\s\s+/g,"")||""},r=function(a){var b=
"";if(0==a.indexOf("/HTML/BODY"))b=e(a);else try{b=eval(a)}catch(B){b=""}return b};try{return b?"meta"==b?c=h(a):"cookie"==b?c=l(a):"param"==b?c=k(a):"content"==b?c=n(a):"event"==b?c=r(a):"var"==b&&(c=d[a]):c=h(a)||l(a)||k(a)||n(a)||r(a)||d[a]||"",c||""}catch(t){return""}};"undefined"==typeof l&&(l={exports:{}});return c}(window);
window[ensightenOptions.ns].data.defineEngine("store",function(){var d={},n=window,k=n.document,l,f=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};d.set=function(a,b){};d.get=function(a){};d.remove=function(a){};d.clear=function(){};try{if("localStorage"in n&&n.localStorage){var c=n.localStorage;d.set=function(a,b){var e,d=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(f(a)){var g=0;for(e=a.length;g<e;g++)c.setItem(a[g],"string"===
typeof b[g]?b[g]:d.stringify(b[g]))}else c.setItem(a,"string"===typeof b?b:d.stringify(b))};d.get=function(a){if(f(a)){var b={},e;var d=0;for(e=a.length;d<e;d++)b[a[d]]=c.getItem(a[d]);return b}return c.getItem(a)};d.remove=function(a){if(f(a)){var b;var e=0;for(b=a.length;e<b;e++)c.removeItem(a[e])}else c.removeItem(a)};d.clear=function(){c.clear()};d.all=function(){return c}}else if("globalStorage"in n&&n.globalStorage)c=n.globalStorage[n.location.hostname],d.set=function(a,b){if(f(a)){var e;var d=
0;for(e=a.length;d<e;d++)c[a[d]]=b[d]}else c[a]=b},d.get=function(a){if(f(a)){var b={},e;var d=0;for(e=a.length;d<e;d++)b[a[d]]=c[a[d]]&&c[a[d]].value;return b}return c[a]&&c[a].value},d.remove=function(a){if(f(a)){var b;var d=0;for(b=a.length;d<b;d++)delete c[a[d]]}else delete c[a]},d.clear=function(){for(var a in c)delete c[a]},d.all=function(){return c};else if(k.documentElement.addBehavior){var h=function(a){return a.replace(g,"___")},n=function(a){return function(){var d=Array.prototype.slice.call(arguments,
0);d.unshift(c);b.appendChild(c);c.addBehavior("#default#userData");c.load("localStorage");d=a.apply(store,d);b.removeChild(c);return d}};try{var a=new ActiveXObject("htmlfile");a.open();a.write('<script>document.w=window\x3c/script><iframe src="/favicon.ico"></frame>');a.close();var b=a.w.frames[0].document;c=b.createElement("div")}catch(e){c=k.createElement("div"),b=k.body}var g=RegExp("[!\"#$%&'()*+,/\\\\:;<=>?@[\\]^`{|}~]","g");d.set=n(function(a,b,c){if(f(b)){var e;var g=0;for(e=b.length;g<e;g++){fixedKey=
h(b[g]);if(void 0===c[g])return d.remove(fixedKey);a.setAttribute(fixedKey,c[g]);a.save("localStorage")}}else{fixedKey=h(b);if(void 0===c)return d.remove(fixedKey);a.setAttribute(fixedKey,c);a.save("localStorage")}});d.get=n(function(a,b){if(f(b)){var c={},d;var e=0;for(d=b.length;e<d;e++){var g=h(b[e]);c[b[e]]=a.getAttribute(g)}return c}b=h(b);return a.getAttribute(b)});d.remove=n(function(a,b){if(f(b)){var c;var d=0;for(c=b.length;d<c;d++)a.removeAttribute(h(b[d])),a.save("localStorage")}else b=
h(b),a.removeAttribute(b),a.save("localStorage")});d.clear=n(function(a){var b=a.XMLDocument.documentElement.attributes;a.load("localStorage");for(var c=0,d;d=b[c];c++)a.removeAttribute(d.name);a.save("localStorage")});d.all=n(function(a){for(var b=a.XMLDocument.documentElement.attributes,c={},d=0,f;f=b[d];++d){var e=h(f.name);c[f.name]=a.getAttribute(e)}return c})}}catch(e){}var m={};for(l in d)m[l]=d[l];m.testStorage=function(){try{var a="tk_"+Math.ceil(5E7*Math.random());m.set(a,"test");if("test"===
m.get(a))return m.remove(a),!0}catch(p){}return!1};d.utils=m;return window[ensightenOptions.ns].data.local=d}());
window[ensightenOptions.ns].data.defineEngine("cookie",function(d,n){var k=function(){return k.get.apply(k,arguments)},l=k.utils={isArray:Array.isArray||function(d){return"[object Array]"===Object.prototype.toString.call(d)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(d){return Array.prototype.slice.call(d)},getKeys:Object.keys||function(d){var c=[],f="";for(f in d)d.hasOwnProperty(f)&&c.push(f);return c},escape:function(d){return String(d).replace(/[,;"\\=\s%]/g,
function(c){return encodeURIComponent(c)})},retrieve:function(d,c){return null==d?c:d},getAllCookies:function(){if(""===d.cookie)return{};for(var f=d.cookie.split("; "),c={},h=0,a=f.length;h<a;h++){var b=f[h].split("=");c[decodeURIComponent(b[0])]=decodeURIComponent(b[1])}return c},set:function(f,c,h){h=h||-1;if(l.isPlainObject(f))for(var a in f)f.hasOwnProperty(a)&&k.set(a,f[a],c);else if(l.isArray(f)){var b;a=0;for(b=f.length;a<b;a++)k.set(f[a],c[a],h)}else{a=h.expires!==n?h.expires:k.defaults.expires||
"";"number"===typeof a&&(a=new Date(a));a=l.isPlainObject(a)&&"toGMTString"in a?";expires="+a.toGMTString():l.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;b=(b=h.path||k.defaults.path)?";path="+b:"";var g=h.domain||k.defaults.domain,g=g?";domain="+g:"";h=h.secure||k.defaults.secure?";secure":"";d.cookie=l.escape(f)+"="+l.escape(c)+a+b+g+h}},get:function(d,c){c=c||n;var f=l.getAllCookies();if(l.isArray(d)){var a={};for(var b=0,g=d.length;b<g;b++)a[d[b]]=l.retrieve(f[d[b]],
c),a[d[b]]===n&&(a[d[b]]=null);return a}a=l.retrieve(f[d],c);return a===n?null:a},getGMTString:function(d){var c=new Date;c.setTime(c.getTime()+864E5*d);return c.toGMTString()}};k.defaults={path:"/",expires:l.getGMTString(90)};k.set=function(d,c){l.set(d,c)};k.remove=function(d){d=l.isArray(d)?d:l.toArray(arguments);for(var c=0,f=d.length;c<f;c++)l.set(d[c],"",{expires:-1})};k.clear=function(){return k.remove(l.getKeys(l.getAllCookies()))};k.get=function(d,c){return l.get(d,c)};k.all=function(){return l.getAllCookies()};
k.utils=l;return window[ensightenOptions.ns].data.cookie=k}(document));
}
		
window[ensightenOptions.ns].ensEvent||(window[ensightenOptions.ns].ensEvent=function(q,w){var h={queue:{},pollQueue:{},pushTrigger:function(a,c){if("[object Array]"===Object.prototype.toString.call(a)){for(var g=0;g<a.length;g++)h.pushTrigger(a[g],c);return!0}if("string"!=typeof a)return!1;this.queue[a]=this.queue[a]||{fn:[]};"function"==typeof c&&this.queue[a].fn.push(c);return!0},callTrigger:function(a,c,g){if("string"!=typeof a)return!1;a=h.queue[a];if("object"==typeof a&&a.fn&&a.fn.length&&(0!=
a.fireOnFirstSet&&c==w||c!=w&&0!=a.fireOnUpdate))for(c=0;c<a.fn.length;c++)a.fn[c].call(this)},setPollOptions:function(a,c,g){this.queue[a]=this.queue[a]||{fn:[]};this.queue[a].fireOnFirstSet=c;this.queue[a].fireOnUpdate=g},callPoll:function(a,c,g,q,r){if("string"==typeof a&&c&&c.length&&!(1>c.length)){for(var n=0;n<c.length;n++)h.setPollOptions(c[n],q,r);h.pushWatch(a,c,g)}},pushWatch:function(a,c,g){this.pollQueue[a]||(this.pollQueue[a]={previousVal:w,eventArr:[],valueFn:g});this.pollQueue[a].eventArr=
this.pollQueue[a].eventArr.concat(c);this.pollQueue[a].valueFn=g},globalWatch:function(){setInterval(function(){for(var a in h.pollQueue){var c=h.pollQueue[a],g=c.valueFn(a);if(c.previousVal!==g ||null==c.previousVal||""==c.previousVal){for(var n=0;n<c.eventArr.length;n++)h.callTrigger.call(q,c.eventArr[n],c.previousVal,g);h.pollQueue[a].previousVal=g}}},500)}};h.globalWatch();return{add:function(a,c){return h.pushTrigger(a,c)},get:function(a){return h.queue[a]},trigger:function(a,c){return h.callTrigger.call(c||q,a)},poll:function(a,c,
g,n,r){r=r||q[ensightenOptions.ns].data.resolve;return h.callPoll(a,c,r,g,n)}}}(window),function(q,w,h){w[q]=h()}("qwery",window[ensightenOptions.ns],function(){function q(){this.c={}}function w(b){return H.g(b)||H.s(b,"(^|\\s+)"+b+"(\\s+|$)",1)}function h(b,d){for(var e=0,f=b.length;e<f;e++)d(b[e])}function a(b){for(var d=[],e=0,f=b.length;e<f;++e)k(b[e])?d=d.concat(b[e]):d[d.length]=b[e];return d}function c(b){for(var d=0,e=b.length,f=[];d<e;d++)f[d]=b[d];return f}function g(b){for(;(b=b.previousSibling)&&
1!=b.nodeType;);return b}function n(b,d,e,f,a,l,k,c,g,h,t){var I,B,m;if(1!==this.nodeType||d&&"*"!==d&&this.tagName&&this.tagName.toLowerCase()!==d||e&&(I=e.match(Q))&&I[1]!==this.id)return!1;if(e&&(m=e.match(R)))for(b=m.length;b--;)if(!w(m[b].slice(1)).test(this.className))return!1;if(g&&u.pseudos[g]&&!u.pseudos[g](this,t))return!1;if(f&&!k)for(B in g=this.attributes,g)if(Object.prototype.hasOwnProperty.call(g,B)&&(g[B].name||B)==a)return this;return f&&!y(l,S(this,a)||"",k)?!1:this}function r(b){return J.g(b)||
J.s(b,b.replace(T,"\\$1"))}function y(b,d,e){switch(b){case "=":return d==e;case "^=":return d.match(x.g("^="+e)||x.s("^="+e,"^"+r(e),1));case "$=":return d.match(x.g("$="+e)||x.s("$="+e,r(e)+"$",1));case "*=":return d.match(x.g(e)||x.s(e,r(e),1));case "~=":return d.match(x.g("~="+e)||x.s("~="+e,"(?:^|\\s+)"+r(e)+"(?:\\s+|$)",1));case "|=":return d.match(x.g("|="+e)||x.s("|="+e,"^"+r(e)+"(-|$)",1))}return 0}function p(b,d){var e=[],f=[],a,l,k,c,g,m=d,t=C.g(b)||C.s(b,b.split(K)),u=b.match(L);if(!t.length)return e;
l=(t=t.slice(0)).pop();t.length&&(a=t[t.length-1].match(M))&&(m=N(d,a[1]));if(!m)return e;c=l.match(E);k=m!==d&&9!==m.nodeType&&u&&/^[+~]$/.test(u[u.length-1])?function(b){for(;m=m.nextSibling;)1==m.nodeType&&(c[1]?c[1]==m.tagName.toLowerCase():1)&&(b[b.length]=m);return b}([]):m.getElementsByTagName(c[1]||"*");a=0;for(l=k.length;a<l;a++)if(g=n.apply(k[a],c))e[e.length]=g;if(!t.length)return e;h(e,function(b){v(b,t,u)&&(f[f.length]=b)});return f}function v(b,d,e,a){function l(b,a,c){for(;c=U[e[a]](c,
b);)if(f(c)&&n.apply(c,d[a].match(E)))if(a){if(k=l(c,a-1,c))return k}else return c}var k;return(k=l(b,d.length-1,b))&&(!a||z(k,a))}function f(b,d){return b&&"object"===typeof b&&(d=b.nodeType)&&(1==d||9==d)}function l(b){var d=[],e,f;e=0;a:for(;e<b.length;++e){for(f=0;f<d.length;++f)if(d[f]==b[e])continue a;d[d.length]=b[e]}return d}function k(b){return"object"===typeof b&&isFinite(b.length)}function N(b,d,e){return 9===b.nodeType?b.getElementById(d):b.ownerDocument&&((e=b.ownerDocument.getElementById(d))&&
z(e,b)&&e||!z(b,b.ownerDocument)&&F('[id="'+d+'"]',b)[0])}function u(b,d){var e,l,g;g=d?"string"==typeof d?u(d)[0]:!d.nodeType&&k(d)?d[0]:d:m;if(!g||!b)return[];if(b===window||f(b))return!d||b!==window&&f(g)&&z(b,g)?[b]:[];if(b&&k(b))return a(b);if(e=b.match(V)){if(e[1])return(l=N(g,e[1]))?[l]:[];if(e[2])return c(g.getElementsByTagName(e[2]));if(W&&e[3])return c(g.getElementsByClassName(e[3]))}return F(b,g)}function t(b,d){return function(e){var f,a;O.test(e)?9!==b.nodeType&&((a=f=b.getAttribute("id"))||
b.setAttribute("id",a="__qwerymeupscotty"),d(b.parentNode||b,'[id="'+a+'"]'+e,!0),f||b.removeAttribute("id")):e.length&&d(b,e,!1)}}var m=document,D=m.documentElement,F,Q=/#([\w\-]+)/,R=/\.[\w\-]+/g,M=/^#([\w\-]+)$/,X=/^([\w]+)?\.([\w\-]+)$/,O=/(^|,)\s*[>~+]/,Y=/^\s+|\s*([,\s\+\~>]|$)\s*/g,A=/[\s\>\+\~]/,P=/(?![\s\w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,T=/([.*+?\^=!:${}()|\[\]\/\\])/g,V=new RegExp(M.source+"|"+/^([\w\-]+)$/.source+"|"+/^\.([\w\-]+)$/.source),L=new RegExp("("+A.source+
")"+P.source,"g"),K=new RegExp(A.source+P.source),E=new RegExp(/^(\*|[a-z0-9]+)?(?:([\.\#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*\~]?\=)['"]?([ \w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),U={" ":function(b){return b&&b!==D&&b.parentNode},">":function(b,d){return b&&b.parentNode==d.parentNode&&b.parentNode},"~":function(b){return b&&b.previousSibling},"+":function(b,d,e,f){return b?(e=g(b))&&(f=g(d))&&e==f&&e:!1}};
q.prototype={g:function(b){return this.c[b]||void 0},s:function(b,d,e){d=e?new RegExp(d):d;return this.c[b]=d}};var H=new q,J=new q,x=new q,C=new q,z="compareDocumentPosition"in D?function(b,d){return 16==(d.compareDocumentPosition(b)&16)}:"contains"in D?function(b,d){d=9===d.nodeType||d==window?D:d;return d!==b&&d.contains(b)}:function(b,d){for(;b=b.parentNode;)if(b===d)return 1;return 0},S=function(){var b=m.createElement("p");return(b.innerHTML='<a href="#x">x</a>',"#x"!=b.firstChild.getAttribute("href"))?
function(b,e){return"class"===e?b.className:"href"===e||"src"===e?b.getAttribute(e,2):b.getAttribute(e)}:function(b,e){return b.getAttribute(e)}}(),W=!!m.getElementsByClassName,Z=m.querySelector&&m.querySelectorAll,aa=function(b,d){var e=[],f,a;try{if(9===d.nodeType||!O.test(b))return c(d.querySelectorAll(b));h(f=b.split(","),t(d,function(b,d){a=b.querySelectorAll(d);1==a.length?e[e.length]=a.item(0):a.length&&(e=e.concat(c(a)))}));return 1<f.length&&1<e.length?l(e):e}catch(ba){}return G(b,d)},G=
function(b,d){var e=[],f,a,c,k;b=b.replace(Y,"$1");if(f=b.match(X)){k=w(f[2]);f=d.getElementsByTagName(f[1]||"*");a=0;for(c=f.length;a<c;a++)k.test(f[a].className)&&(e[e.length]=f[a]);return e}h(f=b.split(","),t(d,function(b,f,l){k=p(f,b);a=0;for(c=k.length;a<c;a++)if(9===b.nodeType||l||z(k[a],d))e[e.length]=k[a]}));return 1<f.length&&1<e.length?l(e):e},A=function(b){"undefined"!==typeof b.useNativeQSA&&(F=b.useNativeQSA?Z?aa:G:G)};A({useNativeQSA:!0});u.configure=A;u.uniq=l;u.is=function(b,d,e){if(f(d))return b==
d;if(k(d))return!!~a(d).indexOf(b);for(var l=d.split(","),c;d=l.pop();)if(c=C.g(d)||C.s(d,d.split(K)),d=d.match(L),c=c.slice(0),n.apply(b,c.pop().match(E))&&(!c.length||v(b,c,d,e)))return!0;return!1};u.pseudos={};return u}),function(){function q(f,a,c){var l;n||(n=window[ensightenOptions.ns].qwery);l=n;if((l=l.call(c,a,c))&&0<l.length){if("_root"==a)f=c;else if(f===c)f=void 0;else{b:{for(var k=l.length,g=0;g<k;g++)if(f===l[g]){l=!0;break b}l=!1}l||(f.parentNode?(r++,f=q(f.parentNode,a,c)):f=void 0)}return f}return!1}
function w(f,a,c,g){p[f.id]||(p[f.id]={});p[f.id][a]||(p[f.id][a]={});p[f.id][a][c]||(p[f.id][a][c]=[]);p[f.id][a][c].push(g)}function h(a,c,g,h){if(h||g)if(h)for(var f=0;f<p[a.id][c][g].length;f++){if(p[a.id][c][g][f]===h){p[a.id][c][g].pop(f,1);break}}else delete p[a.id][c][g];else p[a.id][c]={}}function a(a,c,k){if(p[a][k]){var f=c.target||c.srcElement,l,h,m={},n=h=0;r=0;for(l in p[a][k])p[a][k].hasOwnProperty(l)&&(h=q(f,l,v[a].element))&&g.matchesEvent(k,v[a].element,h,"_root"==l,c)&&(r++,p[a][k][l].match=
h,m[r]=p[a][k][l]);c.stopPropagation=function(){c.cancelBubble=!0};for(h=0;h<=r;h++)if(m[h])for(n=0;n<m[h].length;n++){if(!1===m[h][n].call(m[h].match,c)){g.cancel(c);return}if(c.cancelBubble)return}}}function c(f,c,k,n){function l(c){return function(f){a(t,f,c)}}f instanceof Array||(f=[f]);k||"function"!=typeof c||(k=c,c="_root");var t=this.id,m;for(m=0;m<f.length;m++)p[t]&&p[t][f[m]]||g.addEvent(this,f[m],l(f[m])),n?h(this,f[m],c,k):w(this,f[m],c,k);return this}function g(a,c,k,h){if("string"==
typeof a&&"function"==typeof c||"string"==typeof c)g(document).on(a,c,k,h||!1);if(!(this instanceof g)){for(var f in v)if(v[f].element===a)return v[f];y++;v[y]=new g(a,y);v[y]._on=v[y].on;v[y].on=function(a,c,f,g){var h="function"==typeof c?c:f;if("function"==typeof c?f:g)a=[a],"string"==typeof c&&a.push(c),a.push(function(a){return function(c){c.defaultPrevented||window[ensightenOptions.ns].Delegate.load(this);if(this.nodeName&&"a"!=this.nodeName.toLowerCase())return a.call(this);"undefined"!=typeof c.preventDefault?
c.preventDefault():c.returnValue=!1;a.call(this)}}(h)),this._on.apply(this,a);else return this._on.call(this,a,c,f)};return v[y]}this.element=a;this.id=c}var n,r=0,y=0,p={},v={};g.prototype.on=function(a,g,h){return c.call(this,a,g,h)};g.prototype.off=function(a,g,h){return c.call(this,a,g,h,!0)};g.cancel=function(a){a.preventDefault();a.stopPropagation()};g.addEvent=function(a,c,g){a.element.addEventListener(c,g,"blur"==c||"focus"==c)};g.matchesEvent=function(){return!0};g.load=function(a){setTimeout(function(a,
c){return function(){if(a.nodeName&&"a"==a.nodeName.toLowerCase()){if(c&&/^javascript\s*\:/.test(c))return(new Function(unescape(c))).call(window);c&&(window.location.href=c)}}}(a,a.href||""),750)};window[ensightenOptions.ns].Delegate=g}(),function(q){var w=q.addEvent;q.addEvent=function(h,a,c){if(h.element.addEventListener)return w(h,a,c);"focus"==a&&(a="focusin");"blur"==a&&(a="focusout");h.element.attachEvent("on"+a,c)};q.cancel=function(h){h.preventDefault&&h.preventDefault();h.stopPropagation&&
h.stopPropagation();h.returnValue=!1;h.cancelBubble=!0}}(window[ensightenOptions.ns].Delegate),window[ensightenOptions.ns].on=window[ensightenOptions.ns].Delegate);Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.Cookies=function(){return{domain:""||location.hostname,get:function(a,c){for(var b=document.cookie.split(";"),d=0;d<b.length;d++){var e=b[d].replace(/^\s+/,"").split("\x3d");if(e[0]==a)return c?e[1]:decodeURIComponent(e[1])}return""},set:function(a,c,b){document.cookie=a+"\x3d"+encodeURIComponent(c)+(b?";expires\x3d"+b:"")+";path\x3d/;domain\x3d"+this.domain;
return this.get(a)==c},test:function(a){return this.get(a)?!0:!1}}}()},1877132,454478);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var trackingServer="metrics.nba.com"?"metrics.nba.com":"";var trackingServerSecure="smetrics.nba.com"?"smetrics.nba.com":"";var marketingCloudServer="metrics.nba.com"?"metrics.nba.com":"";var marketingCloudServerSecure="smetrics.nba.com"?"smetrics.nba.com":"";var cookieLifetime=""?"":"";var cookieDomain=""?"":"";window.Visitor=function(q,v){if(!q)throw"Visitor requires Adobe Marketing Cloud Org ID";
var a=this;a.version="1.9.0";var m=window,l=m.Visitor;l.version=a.version;m.s_c_in||(m.s_c_il=[],m.s_c_in=0);a._c="Visitor";a._il=m.s_c_il;a._in=m.s_c_in;a._il[a._in]=a;m.s_c_in++;a.ha={Da:[]};var t=m.document,i=l.Bb;i||(i=null);var D=l.Cb;D||(D=void 0);var j=l.La;j||(j=!0);var k=l.Ja;k||(k=!1);a.da=function(a){var c=0,b,e;if(a)for(b=0;b<a.length;b++)e=a.charCodeAt(b),c=(c<<5)-c+e,c&=c;return c};a.r=function(a,c){var b="0123456789",e="",f="",g,h,i=8,k=10,l=10;c===n&&(w.isClientSideMarketingCloudVisitorID=
j);if(1==a){b+="ABCDEF";for(g=0;16>g;g++)h=Math.floor(Math.random()*i),e+=b.substring(h,h+1),h=Math.floor(Math.random()*i),f+=b.substring(h,h+1),i=16;return e+"-"+f}for(g=0;19>g;g++)h=Math.floor(Math.random()*k),e+=b.substring(h,h+1),0==g&&9==h?k=3:(1==g||2==g)&&10!=k&&2>h?k=10:2<g&&(k=10),h=Math.floor(Math.random()*l),f+=b.substring(h,h+1),0==g&&9==h?l=3:(1==g||2==g)&&10!=l&&2>h?l=10:2<g&&(l=10);return e+f};a.Pa=function(){var a;!a&&m.location&&(a=m.location.hostname);if(a)if(/^[0-9.]+$/.test(a))a=
"";else{var c=a.split("."),b=c.length-1,e=b-1;1<b&&2>=c[b].length&&(2==c[b-1].length||0>",ac,ad,ae,af,ag,ai,al,am,an,ao,aq,ar,as,at,au,aw,ax,az,ba,bb,be,bf,bg,bh,bi,bj,bm,bo,br,bs,bt,bv,bw,by,bz,ca,cc,cd,cf,cg,ch,ci,cl,cm,cn,co,cr,cu,cv,cw,cx,cz,de,dj,dk,dm,do,dz,ec,ee,eg,es,et,eu,fi,fm,fo,fr,ga,gb,gd,ge,gf,gg,gh,gi,gl,gm,gn,gp,gq,gr,gs,gt,gw,gy,hk,hm,hn,hr,ht,hu,id,ie,im,in,io,iq,ir,is,it,je,jo,jp,kg,ki,km,kn,kp,kr,ky,kz,la,lb,lc,li,lk,lr,ls,lt,lu,lv,ly,ma,mc,md,me,mg,mh,mk,ml,mn,mo,mp,mq,mr,ms,mt,mu,mv,mw,mx,my,na,nc,ne,nf,ng,nl,no,nr,nu,nz,om,pa,pe,pf,ph,pk,pl,pm,pn,pr,ps,pt,pw,py,qa,re,ro,rs,ru,rw,sa,sb,sc,sd,se,sg,sh,si,sj,sk,sl,sm,sn,so,sr,st,su,sv,sx,sy,sz,tc,td,tf,tg,th,tj,tk,tl,tm,tn,to,tp,tr,tt,tv,tw,tz,ua,ug,uk,us,uy,uz,va,vc,ve,vg,vi,vn,vu,wf,ws,yt,".indexOf(","+
c[b]+","))&&e--;if(0<e)for(a="";b>=e;)a=c[b]+(a?".":"")+a,b--}return a};a.cookieRead=function(a){var a=encodeURIComponent(a),c=(";"+t.cookie).split(" ").join(";"),b=c.indexOf(";"+a+"\x3d"),e=0>b?b:c.indexOf(";",b+1);return 0>b?"":decodeURIComponent(c.substring(b+2+a.length,0>e?c.length:e))};a.cookieWrite=function(d,c,b){var e=a.cookieLifetime,f,c=""+c,e=e?(""+e).toUpperCase():"";b&&"SESSION"!=e&&"NONE"!=e?(f=""!=c?parseInt(e?e:0,10):-60)?(b=new Date,b.setTime(b.getTime()+1E3*f)):1==b&&(b=new Date,
f=b.getYear(),b.setYear(f+2+(1900>f?1900:0))):b=0;return d&&"NONE"!=e?(t.cookie=encodeURIComponent(d)+"\x3d"+encodeURIComponent(c)+"; path\x3d/;"+(b?" expires\x3d"+b.toGMTString()+";":"")+(a.cookieDomain?" domain\x3d"+a.cookieDomain+";":""),a.cookieRead(d)==c):0};a.h=i;a.J=function(a,c){try{"function"==typeof a?a.apply(m,c):a[1].apply(a[0],c)}catch(b){}};a.Va=function(d,c){c&&(a.h==i&&(a.h={}),a.h[d]==D&&(a.h[d]=[]),a.h[d].push(c))};a.q=function(d,c){if(a.h!=i){var b=a.h[d];if(b)for(;0<b.length;)a.J(b.shift(),
c)}};a.v=function(a,c,b,e){b=encodeURIComponent(c)+"\x3d"+encodeURIComponent(b);c=x.ub(a);a=x.lb(a);if(-1===a.indexOf("?"))return a+"?"+b+c;var f=a.split("?"),a=f[0]+"?",e=x.Ya(f[1],b,e);return a+e+c};a.Oa=function(a,c){var b=RegExp("[\\?\x26#]"+c+"\x3d([^\x26#]*)").exec(a);if(b&&b.length)return decodeURIComponent(b[1])};a.Ua=function(){var d=i,c=m.location.href;try{var b=a.Oa(c,r.Y);if(b)for(var d={},e=b.split("|"),c=0,f=e.length;c<f;c++){var g=e[c].split("\x3d");d[g[0]]=decodeURIComponent(g[1])}return d}catch(h){}};
a.Ma=function(){var d=a.Ua();if(d){var c=d[n],b=a.setMarketingCloudVisitorID;c&&c.match(r.u)&&b(c);a.j(s,-1);d=d[p];c=a.setAnalyticsVisitorID;d&&d.match(r.u)&&c(d)}};a.Ta=function(d){function c(d){x.ob(d)&&a.setCustomerIDs(d)}function b(d){d=d||{};a._supplementalDataIDCurrent=d.supplementalDataIDCurrent||"";a._supplementalDataIDCurrentConsumed=d.supplementalDataIDCurrentConsumed||{};a._supplementalDataIDLast=d.supplementalDataIDLast||"";a._supplementalDataIDLastConsumed=d.supplementalDataIDLastConsumed||
{}}d&&d[a.marketingCloudOrgID]&&(d=d[a.marketingCloudOrgID],c(d.customerIDs),b(d.sdid))};a.l=i;a.Ra=function(d,c,b,e){c=a.v(c,"d_fieldgroup",d,1);e.url=a.v(e.url,"d_fieldgroup",d,1);e.m=a.v(e.m,"d_fieldgroup",d,1);w.d[d]=j;e===Object(e)&&e.m&&"XMLHttpRequest"===a.ja.C.D?a.ja.hb(e,b,d):a.useCORSOnly||a.ga(d,c,b)};a.ga=function(d,c,b){var e=0,f=0,g;if(c&&t){for(g=0;!e&&2>g;){try{e=(e=t.getElementsByTagName(0<g?"HEAD":"head"))&&0<e.length?e[0]:0}catch(h){e=0}g++}if(!e)try{t.body&&(e=t.body)}catch(k){e=
0}if(e)for(g=0;!f&&2>g;){try{f=t.createElement(0<g?"SCRIPT":"script")}catch(l){f=0}g++}}!c||!e||!f?b&&b():(f.type="text/javascript",f.src=c,e.firstChild?e.insertBefore(f,e.firstChild):e.appendChild(f),e=a.loadTimeout,o.d[d]={requestStart:o.o(),url:c,sa:e,qa:o.wa(),ra:0},b&&(a.l==i&&(a.l={}),a.l[d]=setTimeout(function(){b(j)},e)),a.ha.Da.push(c))};a.Na=function(d){a.l!=i&&a.l[d]&&(clearTimeout(a.l[d]),a.l[d]=0)};a.ea=k;a.fa=k;a.isAllowed=function(){if(!a.ea&&(a.ea=j,a.cookieRead(a.cookieName)||a.cookieWrite(a.cookieName,
"T",1)))a.fa=j;return a.fa};a.b=i;a.c=i;var E=l.Tb;E||(E="MC");var n=l.Zb;n||(n="MCMID");var G=l.Ub;G||(G="MCCIDH");var J=l.Xb;J||(J="MCSYNCS");var H=l.Yb;H||(H="MCSYNCSOP");var I=l.Vb;I||(I="MCIDTS");var A=l.Wb;A||(A="MCOPTOUT");var C=l.Rb;C||(C="A");var p=l.Ob;p||(p="MCAID");var B=l.Sb;B||(B="AAM");var y=l.Qb;y||(y="MCAAMLH");var s=l.Pb;s||(s="MCAAMB");var u=l.$b;u||(u="NONE");a.L=0;a.ca=function(){if(!a.L){var d=a.version;a.audienceManagerServer&&(d+="|"+a.audienceManagerServer);a.audienceManagerServerSecure&&
(d+="|"+a.audienceManagerServerSecure);a.L=a.da(d)}return a.L};a.ia=k;a.f=function(){if(!a.ia){a.ia=j;var d=a.ca(),c=k,b=a.cookieRead(a.cookieName),e,f,g,h,l=new Date;a.b==i&&(a.b={});if(b&&"T"!=b){b=b.split("|");b[0].match(/^[\-0-9]+$/)&&(parseInt(b[0],10)!=d&&(c=j),b.shift());1==b.length%2&&b.pop();for(d=0;d<b.length;d+=2)if(e=b[d].split("-"),f=e[0],g=b[d+1],1<e.length?(h=parseInt(e[1],10),e=0<e[1].indexOf("s")):(h=0,e=k),c&&(f==G&&(g=""),0<h&&(h=l.getTime()/1E3-60)),f&&g&&(a.e(f,g,1),0<h&&(a.b["expire"+
f]=h+(e?"s":""),l.getTime()>=1E3*h||e&&!a.cookieRead(a.sessionCookieName))))a.c||(a.c={}),a.c[f]=j}c=a.loadSSL?!!a.trackingServerSecure:!!a.trackingServer;if(!a.a(p)&&c&&(b=a.cookieRead("s_vi")))b=b.split("|"),1<b.length&&0<=b[0].indexOf("v1")&&(g=b[1],d=g.indexOf("["),0<=d&&(g=g.substring(0,d)),g&&g.match(r.u)&&a.e(p,g))}};a.Xa=function(){var d=a.ca(),c,b;for(c in a.b)!Object.prototype[c]&&a.b[c]&&"expire"!=c.substring(0,6)&&(b=a.b[c],d+=(d?"|":"")+c+(a.b["expire"+c]?"-"+a.b["expire"+c]:"")+"|"+
b);a.cookieWrite(a.cookieName,d,1)};a.a=function(d,c){return a.b!=i&&(c||!a.c||!a.c[d])?a.b[d]:i};a.e=function(d,c,b){a.b==i&&(a.b={});a.b[d]=c;b||a.Xa()};a.Qa=function(d,c){var b=a.a(d,c);return b?b.split("*"):i};a.Wa=function(d,c,b){a.e(d,c?c.join("*"):"",b)};a.Ib=function(d,c){var b=a.Qa(d,c);if(b){var e={},f;for(f=0;f<b.length;f+=2)e[b[f]]=b[f+1];return e}return i};a.Kb=function(d,c,b){var e=i,f;if(c)for(f in e=[],c)Object.prototype[f]||(e.push(f),e.push(c[f]));a.Wa(d,e,b)};a.j=function(d,c,b){var e=
new Date;e.setTime(e.getTime()+1E3*c);a.b==i&&(a.b={});a.b["expire"+d]=Math.floor(e.getTime()/1E3)+(b?"s":"");0>c?(a.c||(a.c={}),a.c[d]=j):a.c&&(a.c[d]=k);b&&(a.cookieRead(a.sessionCookieName)||a.cookieWrite(a.sessionCookieName,"1"))};a.ba=function(a){if(a&&("object"==typeof a&&(a=a.d_mid?a.d_mid:a.visitorID?a.visitorID:a.id?a.id:a.uuid?a.uuid:""+a),a&&(a=a.toUpperCase(),"NOTARGET"==a&&(a=u)),!a||a!=u&&!a.match(r.u)))a="";return a};a.k=function(d,c){a.Na(d);a.i!=i&&(a.i[d]=k);o.d[d]&&(o.d[d].zb=o.o(),
o.I(d));w.d[d]&&w.Fa(d,k);if(d==E){w.isClientSideMarketingCloudVisitorID!==j&&(w.isClientSideMarketingCloudVisitorID=k);var b=a.a(n);if(!b){b="object"==typeof c&&c.mid?c.mid:a.ba(c);if(!b){if(a.B){a.getAnalyticsVisitorID(i,k,j);return}b=a.r(0,n)}a.e(n,b)}if(!b||b==u)b="";"object"==typeof c&&((c.d_region||c.dcs_region||c.d_blob||c.blob)&&a.k(B,c),a.B&&c.mid&&a.k(C,{id:c.id}));a.q(n,[b])}if(d==B&&"object"==typeof c){b=604800;c.id_sync_ttl!=D&&c.id_sync_ttl&&(b=parseInt(c.id_sync_ttl,10));var e=a.a(y);
e||((e=c.d_region)||(e=c.dcs_region),e&&(a.j(y,b),a.e(y,e)));e||(e="");a.q(y,[e]);e=a.a(s);if(c.d_blob||c.blob)(e=c.d_blob)||(e=c.blob),a.j(s,b),a.e(s,e);e||(e="");a.q(s,[e]);!c.error_msg&&a.A&&a.e(G,a.A)}if(d==C){b=a.a(p);b||((b=a.ba(c))?b!==u&&a.j(s,-1):b=u,a.e(p,b));if(!b||b==u)b="";a.q(p,[b])}a.idSyncDisableSyncs?z.xa=j:(z.xa=k,b={},b.ibs=c.ibs,b.subdomain=c.subdomain,z.vb(b));if(c===Object(c)){var f;a.isAllowed()&&(f=a.a(A));f||(f=u,c.d_optout&&c.d_optout instanceof Array&&(f=c.d_optout.join(",")),
b=parseInt(c.d_ottl,10),isNaN(b)&&(b=7200),a.j(A,b,j),a.e(A,f));a.q(A,[f])}};a.i=i;a.s=function(d,c,b,e,f){var g="",h,k=x.nb(d);if(a.isAllowed()&&(a.f(),g=a.a(d,K[d]===j),a.disableThirdPartyCalls&&!g&&(d===n?(g=a.r(0,n),a.setMarketingCloudVisitorID(g)):d===p&&!k&&(g="",a.setAnalyticsVisitorID(g))),(!g||a.c&&a.c[d])&&(!a.disableThirdPartyCalls||k)))if(d==n||d==A?h=E:d==y||d==s?h=B:d==p&&(h=C),h){if(c&&(a.i==i||!a.i[h]))a.i==i&&(a.i={}),a.i[h]=j,a.Ra(h,c,function(b,c){if(!a.a(d))if(o.d[h]&&(o.d[h].timeout=
o.o(),o.d[h].mb=!!b,o.I(h)),c===Object(c)&&!a.useCORSOnly)a.ga(h,c.url,c.G);else{b&&w.Fa(h,j);var e="";d==n?e=a.r(0,n):h==B&&(e={error_msg:"timeout"});a.k(h,e)}},f);if(g)return g;a.Va(d,b);c||a.k(h,{id:u});return""}if((d==n||d==p)&&g==u)g="",e=j;b&&e&&a.J(b,[g]);return g};a._setMarketingCloudFields=function(d){a.f();a.k(E,d)};a.setMarketingCloudVisitorID=function(d){a._setMarketingCloudFields(d)};a.B=k;a.getMarketingCloudVisitorID=function(d,c){if(a.isAllowed()){a.marketingCloudServer&&0>a.marketingCloudServer.indexOf(".demdex.net")&&
(a.B=j);var b=a.z("_setMarketingCloudFields");return a.s(n,b.url,d,c,b)}return""};a.Sa=function(){a.getAudienceManagerBlob()};l.AuthState={UNKNOWN:0,AUTHENTICATED:1,LOGGED_OUT:2};a.w={};a.aa=k;a.A="";a.setCustomerIDs=function(d){if(a.isAllowed()&&d){a.f();var c,b;for(c in d)if(!Object.prototype[c]&&(b=d[c]))if("object"==typeof b){var e={};b.id&&(e.id=b.id);b.authState!=D&&(e.authState=b.authState);a.w[c]=e}else a.w[c]={id:b};var d=a.getCustomerIDs(),e=a.a(G),f="";e||(e=0);for(c in d)Object.prototype[c]||
(b=d[c],f+=(f?"|":"")+c+"|"+(b.id?b.id:"")+(b.authState?b.authState:""));a.A=a.da(f);a.A!=e&&(a.aa=j,a.Sa())}};a.getCustomerIDs=function(){a.f();var d={},c,b;for(c in a.w)Object.prototype[c]||(b=a.w[c],d[c]||(d[c]={}),b.id&&(d[c].id=b.id),d[c].authState=b.authState!=D?b.authState:l.AuthState.UNKNOWN);return d};a._setAnalyticsFields=function(d){a.f();a.k(C,d)};a.setAnalyticsVisitorID=function(d){a._setAnalyticsFields(d)};a.getAnalyticsVisitorID=function(d,c,b){if(a.isAllowed()){var e="";b||(e=a.getMarketingCloudVisitorID(function(){a.getAnalyticsVisitorID(d,
j)}));if(e||b){var f=b?a.marketingCloudServer:a.trackingServer,g="";a.loadSSL&&(b?a.marketingCloudServerSecure&&(f=a.marketingCloudServerSecure):a.trackingServerSecure&&(f=a.trackingServerSecure));var h={};if(f){var f="http"+(a.loadSSL?"s":"")+"://"+f+"/id",e="d_visid_ver\x3d"+a.version+"\x26mcorgid\x3d"+encodeURIComponent(a.marketingCloudOrgID)+(e?"\x26mid\x3d"+encodeURIComponent(e):"")+(a.idSyncDisable3rdPartySyncing?"\x26d_coppa\x3dtrue":""),i=["s_c_il",a._in,"_set"+(b?"MarketingCloud":"Analytics")+
"Fields"],g=f+"?"+e+"\x26callback\x3ds_c_il%5B"+a._in+"%5D._set"+(b?"MarketingCloud":"Analytics")+"Fields";h.m=f+"?"+e;h.na=i}h.url=g;return a.s(b?n:p,g,d,c,h)}}return""};a._setAudienceManagerFields=function(d){a.f();a.k(B,d)};a.z=function(d){var c=a.audienceManagerServer,b="",e=a.a(n),f=a.a(s,j),g=a.a(p),g=g&&g!=u?"\x26d_cid_ic\x3dAVID%01"+encodeURIComponent(g):"";a.loadSSL&&a.audienceManagerServerSecure&&(c=a.audienceManagerServerSecure);if(c){var b=a.getCustomerIDs(),h,i;if(b)for(h in b)Object.prototype[h]||
(i=b[h],g+="\x26d_cid_ic\x3d"+encodeURIComponent(h)+"%01"+encodeURIComponent(i.id?i.id:"")+(i.authState?"%01"+i.authState:""));d||(d="_setAudienceManagerFields");c="http"+(a.loadSSL?"s":"")+"://"+c+"/id";e="d_visid_ver\x3d"+a.version+"\x26d_rtbd\x3djson\x26d_ver\x3d2"+(!e&&a.B?"\x26d_verify\x3d1":"")+"\x26d_orgid\x3d"+encodeURIComponent(a.marketingCloudOrgID)+"\x26d_nsid\x3d"+(a.idSyncContainerID||0)+(e?"\x26d_mid\x3d"+encodeURIComponent(e):"")+(a.idSyncDisable3rdPartySyncing?"\x26d_coppa\x3dtrue":
"")+(f?"\x26d_blob\x3d"+encodeURIComponent(f):"")+g;f=["s_c_il",a._in,d];b=c+"?"+e+"\x26d_cb\x3ds_c_il%5B"+a._in+"%5D."+d;return{url:b,m:c+"?"+e,na:f}}return{url:b}};a.getAudienceManagerLocationHint=function(d,c){if(a.isAllowed()&&a.getMarketingCloudVisitorID(function(){a.getAudienceManagerLocationHint(d,j)})){var b=a.a(p);b||(b=a.getAnalyticsVisitorID(function(){a.getAudienceManagerLocationHint(d,j)}));if(b)return b=a.z(),a.s(y,b.url,d,c,b)}return""};a.getAudienceManagerBlob=function(d,c){if(a.isAllowed()&&
a.getMarketingCloudVisitorID(function(){a.getAudienceManagerBlob(d,j)})){var b=a.a(p);b||(b=a.getAnalyticsVisitorID(function(){a.getAudienceManagerBlob(d,j)}));if(b){var b=a.z(),e=b.url;a.aa&&a.j(s,-1);return a.s(s,e,d,c,b)}}return""};a._supplementalDataIDCurrent="";a._supplementalDataIDCurrentConsumed={};a._supplementalDataIDLast="";a._supplementalDataIDLastConsumed={};a.getSupplementalDataID=function(d,c){!a._supplementalDataIDCurrent&&!c&&(a._supplementalDataIDCurrent=a.r(1));var b=a._supplementalDataIDCurrent;
a._supplementalDataIDLast&&!a._supplementalDataIDLastConsumed[d]?(b=a._supplementalDataIDLast,a._supplementalDataIDLastConsumed[d]=j):b&&(a._supplementalDataIDCurrentConsumed[d]&&(a._supplementalDataIDLast=a._supplementalDataIDCurrent,a._supplementalDataIDLastConsumed=a._supplementalDataIDCurrentConsumed,a._supplementalDataIDCurrent=b=!c?a.r(1):"",a._supplementalDataIDCurrentConsumed={}),b&&(a._supplementalDataIDCurrentConsumed[d]=j));return b};l.OptOut={GLOBAL:"global"};a.getOptOut=function(d,c){if(a.isAllowed()){var b=
a.z("_setMarketingCloudFields");return a.s(A,b.url,d,c,b)}return""};a.isOptedOut=function(d,c,b){return a.isAllowed()?(c||(c=l.OptOut.GLOBAL),(b=a.getOptOut(function(b){a.J(d,[b==l.OptOut.GLOBAL||0<=b.indexOf(c)])},b))?b==l.OptOut.GLOBAL||0<=b.indexOf(c):i):k};a.appendVisitorIDsTo=function(d){for(var c=r.Y,b=[[n,a.a(n)],[p,a.a(p)]],e="",f=0,g=b.length;f<g;f++){var h=b[f],j=h[0],h=h[1];h!=i&&h!==u&&(e=e?e+="|":e,e+=j+"\x3d"+encodeURIComponent(h))}try{return a.v(d,c,e)}catch(k){return d}};var r={p:!!m.postMessage,
Ia:1,$:864E5,Y:"adobe_mc",u:/^[0-9a-fA-F\-]+$/};a.Db=r;a.la={postMessage:function(a,c,b){var e=1;c&&(r.p?b.postMessage(a,c.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):c&&(b.location=c.replace(/#.*$/,"")+"#"+ +new Date+e++ +"\x26"+a))},T:function(a,c){var b;try{if(r.p)if(a&&(b=function(b){if("string"===typeof c&&b.origin!==c||"[object Function]"===Object.prototype.toString.call(c)&&!1===c(b.origin))return!1;a(b)}),window.addEventListener)window[a?"addEventListener":"removeEventListener"]("message",b,!1);
else window[a?"attachEvent":"detachEvent"]("onmessage",b)}catch(e){}}};var x={M:function(){if(t.addEventListener)return function(a,c,b){a.addEventListener(c,function(a){"function"===typeof b&&b(a)},k)};if(t.attachEvent)return function(a,c,b){a.attachEvent("on"+c,function(a){"function"===typeof b&&b(a)})}}(),map:function(a,c){if(Array.prototype.map)return a.map(c);if(void 0===a||a===i)throw new TypeError;var b=Object(a),e=b.length>>>0;if("function"!==typeof c)throw new TypeError;for(var f=Array(e),
g=0;g<e;g++)g in b&&(f[g]=c.call(c,b[g],g,b));return f},gb:function(a,c){return this.map(a,function(a){return encodeURIComponent(a)}).join(c)},ub:function(a){var c=a.indexOf("#");return 0<c?a.substr(c):""},lb:function(a){var c=a.indexOf("#");return 0<c?a.substr(0,c):a},Ya:function(a,c,b){a=a.split("\x26");b=b!=i?b:a.length;a.splice(b,0,c);return a.join("\x26")},nb:function(d,c,b){if(d!==p)return k;c||(c=a.trackingServer);b||(b=a.trackingServerSecure);d=a.loadSSL?b:c;return"string"===typeof d&&d.length?
0>d.indexOf("2o7.net")&&0>d.indexOf("omtrdc.net"):k},ob:function(a){return Boolean(a&&a===Object(a))}};a.Jb=x;var L={C:function(){var a="none",c=j;"undefined"!==typeof XMLHttpRequest&&XMLHttpRequest===Object(XMLHttpRequest)&&("withCredentials"in new XMLHttpRequest?a="XMLHttpRequest":(new Function("/*@cc_on return /^10/.test(@_jscript_version) @*/"))()?a="XMLHttpRequest":"undefined"!==typeof XDomainRequest&&XDomainRequest===Object(XDomainRequest)&&(c=k),0<Object.prototype.toString.call(window.Ab).indexOf("Constructor")&&
(c=k));return{D:a,Mb:c}}(),ib:function(){return"none"===this.C.D?i:new window[this.C.D]},hb:function(d,c,b){var e=this;c&&(d.G=c);try{var f=this.ib();f.open("get",d.m+"\x26ts\x3d"+(new Date).getTime(),j);"XMLHttpRequest"===this.C.D&&(f.withCredentials=j,f.timeout=a.loadTimeout,f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),f.onreadystatechange=function(){if(4===this.readyState&&200===this.status)a:{var a;try{if(a=JSON.parse(this.responseText),a!==Object(a)){e.n(d,i,"Response is not JSON");
break a}}catch(b){e.n(d,b,"Error parsing response as JSON");break a}try{for(var c=d.na,f=window,g=0;g<c.length;g++)f=f[c[g]];f(a)}catch(j){e.n(d,j,"Error forming callback function")}}});f.onerror=function(a){e.n(d,a,"onerror")};f.ontimeout=function(a){e.n(d,a,"ontimeout")};f.send();o.d[b]={requestStart:o.o(),url:d.m,sa:f.timeout,qa:o.wa(),ra:1};a.ha.Da.push(d.m)}catch(g){this.n(d,g,"try-catch")}},n:function(d,c,b){a.CORSErrors.push({Nb:d,error:c,description:b});d.G&&("ontimeout"===b?d.G(j):d.G(k,
d))}};a.ja=L;var z={Ka:3E4,Z:649,Ha:k,id:i,S:[],P:i,va:function(a){if("string"===typeof a)return a=a.split("/"),a[0]+"//"+a[2]},g:i,url:i,jb:function(){var d="http://fast.",c="?d_nsid\x3d"+a.idSyncContainerID+"#"+encodeURIComponent(t.location.href);this.g||(this.g="nosubdomainreturned");a.loadSSL&&(d=a.idSyncSSLUseAkamai?"https://fast.":"https://");d=d+this.g+".demdex.net/dest5.html"+c;this.P=this.va(d);this.id="destination_publishing_iframe_"+this.g+"_"+a.idSyncContainerID;return d},ab:function(){var d=
"?d_nsid\x3d"+a.idSyncContainerID+"#"+encodeURIComponent(t.location.href);"string"===typeof a.K&&a.K.length&&(this.id="destination_publishing_iframe_"+(new Date).getTime()+"_"+a.idSyncContainerID,this.P=this.va(a.K),this.url=a.K+d)},xa:i,ta:k,V:k,F:i,ac:i,tb:i,bc:i,U:k,H:[],rb:[],sb:[],za:r.p?15:100,Q:[],pb:[],oa:j,Ca:k,Ba:function(){return!a.idSyncDisable3rdPartySyncing&&(this.ta||a.Fb)&&this.g&&"nosubdomainreturned"!==this.g&&this.url&&!this.V},N:function(){function a(){e=document.createElement("iframe");
e.sandbox="allow-scripts allow-same-origin";e.title="Adobe ID Syncing iFrame";e.id=b.id;e.style.cssText="display: none; width: 0; height: 0;";e.src=b.url;b.tb=j;c();document.body.appendChild(e)}function c(){x.M(e,"load",function(){e.className="aamIframeLoaded";b.F=j;b.t()})}this.V=j;var b=this,e=document.getElementById(this.id);e?"IFRAME"!==e.nodeName?(this.id+="_2",a()):"aamIframeLoaded"!==e.className?c():(this.F=j,this.ya=e,this.t()):a();this.ya=e},t:function(d){var c=this;d===Object(d)&&(this.Q.push(d),
this.wb(d));if((this.Ca||!r.p||this.F)&&this.Q.length)this.I(this.Q.shift()),this.t();!a.idSyncDisableSyncs&&this.F&&this.H.length&&!this.U&&(this.Ha||(this.Ha=j,setTimeout(function(){c.za=r.p?15:150},this.Ka)),this.U=j,this.Ea())},wb:function(a){var c,b,e;if((c=a.ibs)&&c instanceof Array&&(b=c.length))for(a=0;a<b;a++)e=c[a],e.syncOnPage&&this.pa(e,"","syncOnPage")},I:function(a){var c=encodeURIComponent,b,e,f,g,h;if((b=a.ibs)&&b instanceof Array&&(e=b.length))for(f=0;f<e;f++)g=b[f],h=[c("ibs"),c(g.id||
""),c(g.tag||""),x.gb(g.url||[],","),c(g.ttl||""),"","",g.fireURLSync?"true":"false"],g.syncOnPage||(this.oa?this.ma(h.join("|")):g.fireURLSync&&this.pa(g,h.join("|")));this.pb.push(a)},pa:function(d,c,b){var e=(b="syncOnPage"===b?j:k)?H:J;a.f();var f=a.a(e),g=k,h=k,i=Math.ceil((new Date).getTime()/r.$);f?(f=f.split("*"),h=this.xb(f,d.id,i),g=h.eb,h=h.fb,(!g||!h)&&this.ua(b,d,c,f,e,i)):(f=[],this.ua(b,d,c,f,e,i))},xb:function(a,c,b){var e=k,f=k,g,h,i;for(h=0;h<a.length;h++)g=a[h],i=parseInt(g.split("-")[1],
10),g.match("^"+c+"-")?(e=j,b<i?f=j:(a.splice(h,1),h--)):b>=i&&(a.splice(h,1),h--);return{eb:e,fb:f}},qb:function(a){if(a.join("*").length>this.Z)for(a.sort(function(a,b){return parseInt(a.split("-")[1],10)-parseInt(b.split("-")[1],10)});a.join("*").length>this.Z;)a.shift()},ua:function(d,c,b,e,f,g){var h=this;if(d){if("img"===c.tag){var d=c.url,b=a.loadSSL?"https:":"http:",j,k,l;for(e=0,j=d.length;e<j;e++){k=d[e];l=/^\/\//.test(k);var m=new Image;x.M(m,"load",function(b,c,d,e){return function(){h.S[b]=
i;a.f();var g=a.a(f),j=[];if(g){var g=g.split("*"),k,l,m;for(k=0,l=g.length;k<l;k++)m=g[k],m.match("^"+c.id+"-")||j.push(m)}h.Ga(j,c,d,e)}}(this.S.length,c,f,g));m.src=(l?b:"")+k;this.S.push(m)}}}else this.ma(b),this.Ga(e,c,f,g)},ma:function(d){var c=encodeURIComponent;this.H.push((a.Gb?c("---destpub-debug---"):c("---destpub---"))+d)},Ga:function(d,c,b,e){d.push(c.id+"-"+(e+Math.ceil(c.ttl/60/24)));this.qb(d);a.e(b,d.join("*"))},Ea:function(){var d=this,c;this.H.length?(c=this.H.shift(),a.la.postMessage(c,
this.url,this.ya.contentWindow),this.rb.push(c),setTimeout(function(){d.Ea()},this.za)):this.U=k},T:function(a){var c=/^---destpub-to-parent---/;"string"===typeof a&&c.test(a)&&(c=a.replace(c,"").split("|"),"canSetThirdPartyCookies"===c[0]&&(this.oa="true"===c[1]?j:k,this.Ca=j,this.t()),this.sb.push(a))},vb:function(d){if(this.url===i||d.subdomain&&"nosubdomainreturned"===this.g)this.g="string"===typeof a.ka&&a.ka.length?a.ka:d.subdomain||"",this.url=this.jb();d.ibs instanceof Array&&d.ibs.length&&
(this.ta=j);this.Ba()&&(a.idSyncAttachIframeOnWindowLoad?(l.X||"complete"===t.readyState||"loaded"===t.readyState)&&this.N():this.Za());"function"===typeof a.idSyncIDCallResult?a.idSyncIDCallResult(d):this.t(d);"function"===typeof a.idSyncAfterIDCallResult&&a.idSyncAfterIDCallResult(d)},$a:function(d,c){return a.Hb||!d||c-d>r.Ia},Za:function(){function a(){c.V||(document.body?c.N():setTimeout(a,30))}var c=this;a()}};a.Eb=z;a.timeoutMetricsLog=[];var o={cb:window.performance&&window.performance.timing?
1:0,Aa:window.performance&&window.performance.timing?window.performance.timing:i,W:i,O:i,d:{},R:[],send:function(d){if(a.takeTimeoutMetrics&&d===Object(d)){var c=[],b=encodeURIComponent,e;for(e in d)d.hasOwnProperty(e)&&c.push(b(e)+"\x3d"+b(d[e]));d="http"+(a.loadSSL?"s":"")+"://dpm.demdex.net/event?d_visid_ver\x3d"+a.version+"\x26d_visid_stg_timeout\x3d"+a.loadTimeout+"\x26"+c.join("\x26")+"\x26d_orgid\x3d"+b(a.marketingCloudOrgID)+"\x26d_timingapi\x3d"+this.cb+"\x26d_winload\x3d"+this.kb()+"\x26d_ld\x3d"+
this.o();(new Image).src=d;a.timeoutMetricsLog.push(d)}},kb:function(){this.O===i&&(this.O=this.Aa?this.W-this.Aa.navigationStart:this.W-l.bb);return this.O},o:function(){return(new Date).getTime()},I:function(a){var c=this.d[a],b={};b.d_visid_stg_timeout_captured=c.sa;b.d_visid_cors=c.ra;b.d_fieldgroup=a;b.d_settimeout_overriden=c.qa;c.timeout?c.mb?(b.d_visid_timedout=1,b.d_visid_timeout=c.timeout-c.requestStart,b.d_visid_response=-1):(b.d_visid_timedout="n/a",b.d_visid_timeout="n/a",b.d_visid_response=
"n/a"):(b.d_visid_timedout=0,b.d_visid_timeout=-1,b.d_visid_response=c.zb-c.requestStart);b.d_visid_url=c.url;l.X?this.send(b):this.R.push(b);delete this.d[a]},yb:function(){for(var a=0,c=this.R.length;a<c;a++)this.send(this.R[a])},wa:function(){return"function"===typeof setTimeout.toString?-1<setTimeout.toString().indexOf("[native code]")?0:1:-1}};a.Lb=o;var w={isClientSideMarketingCloudVisitorID:i,MCIDCallTimedOut:i,AnalyticsIDCallTimedOut:i,AAMIDCallTimedOut:i,d:{},Fa:function(a,c){switch(a){case E:c===
k?this.MCIDCallTimedOut!==j&&(this.MCIDCallTimedOut=k):this.MCIDCallTimedOut=c;break;case C:c===k?this.AnalyticsIDCallTimedOut!==j&&(this.AnalyticsIDCallTimedOut=k):this.AnalyticsIDCallTimedOut=c;break;case B:c===k?this.AAMIDCallTimedOut!==j&&(this.AAMIDCallTimedOut=k):this.AAMIDCallTimedOut=c}}};a.isClientSideMarketingCloudVisitorID=function(){return w.isClientSideMarketingCloudVisitorID};a.MCIDCallTimedOut=function(){return w.MCIDCallTimedOut};a.AnalyticsIDCallTimedOut=function(){return w.AnalyticsIDCallTimedOut};
a.AAMIDCallTimedOut=function(){return w.AAMIDCallTimedOut};a.idSyncGetOnPageSyncInfo=function(){a.f();return a.a(H)};0>q.indexOf("@")&&(q+="@AdobeOrg");a.marketingCloudOrgID=q;a.cookieName="AMCV_"+q;a.sessionCookieName="AMCVS_"+q;a.cookieDomain=a.Pa();a.cookieDomain==m.location.hostname&&(a.cookieDomain="");a.loadSSL=0<=m.location.protocol.toLowerCase().indexOf("https");a.loadTimeout=3E4;a.CORSErrors=[];a.marketingCloudServer=a.audienceManagerServer="dpm.demdex.net";var K={};K[y]=j;K[s]=j;a.Ma();
if(v&&"object"==typeof v){for(var F in v)!Object.prototype[F]&&(a[F]=v[F]);a.idSyncContainerID=a.idSyncContainerID||0;a.f();L=a.a(I);F=Math.ceil((new Date).getTime()/r.$);!a.idSyncDisableSyncs&&z.$a(L,F)&&(a.j(s,-1),a.e(I,F));a.getMarketingCloudVisitorID();a.getAudienceManagerLocationHint();a.getAudienceManagerBlob();a.Ta(a.serverState)}if(!a.idSyncDisableSyncs){z.ab();x.M(window,"load",function(){l.X=j;o.W=o.o();o.yb();var a=z;a.Ba()&&a.N()});try{a.la.T(function(a){z.T(a.data)},z.P)}catch(M){}}};
Visitor.getInstance=function(q,v){var a,m=window.s_c_il,l;0>q.indexOf("@")&&(q+="@AdobeOrg");if(m)for(l=0;l<m.length;l++)if((a=m[l])&&"Visitor"==a._c&&a.marketingCloudOrgID==q)return a;return new Visitor(q,v)};(function(){function q(){v.X=a}var v=window.Visitor,a=v.La,m=v.Ja;a||(a=!0);m||(m=!1);window.addEventListener?window.addEventListener("load",q):window.attachEvent&&window.attachEvent("onload",q);v.bb=(new Date).getTime()})();window.visitor=Visitor.getInstance("7FF852E2556756057F000101@AdobeOrg",
{"trackingServer":trackingServer,"trackingServerSecure":trackingServerSecure,"marketingCloudServer":marketingCloudServer,"marketingCloudServerSecure":marketingCloudServerSecure,"cookieLifetime":cookieLifetime,"cookieDomain":cookieDomain})},1877131,419008);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();